LOG_LEVEL_VERBOSE = 1
LOG_LEVEL_INFO = 2
LOG_LEVEL_DEBUG = 3
LOG_LEVEL_WARN = 4
LOG_LEVEL_ERROR = 5

TEST_CRAWL_URL = "http://finance.naver.com/item/main.nhn?code=128940"

COMPANY_INFO_ELEMENTS_CLASS_NAME = "wrap_company"
STOCK_PRICE_ELEMENTS_CLASS_NAME = "rate_info"
STOCK_NUMBER_CLASS_NAME = "no_down"

TAG_SPAN = "span"